language: node_js
node_js:
  - 14
install:
  - npm install
before_script:
  - npm run lint
after_success:
  - npm start
deploy:
  - provider: surge
    project: ./Server/public/
    domain: kilogram-team3.surge.sh
    skip_cleanup: true
