language: node_js
node_js:
  - 14
install:
  - npm install
before_script:
  - npm run lint
after_success:
  - npm run build
deploy:
  - provider: surge
    project: ./server/public/
    domain: kilogram-team3.surge.sh
